### PR TITLE
Filter button and booking page.

### PR DESCRIPTION
**Pull request by kikoDevv**
Filter btn added to the challenges page and linked to filter menu. book-page-one design is done for now. some files how to be compiled to sass. function added for the filter menu to switch between on and off, the same has to be done with filterBtn.

### CODE REVIEW

**Comment by EmpyreanMist** [comment]
Book.css file is not needed, please delete it and only use scss files that compiles to main.css

**Review by SpinalGlitter — APPROVED** [review]
it looks good.

**Review by EmpyreanMist — CHANGES_REQUESTED** [review]
Book.css file is not needed, please delete it and only use scss files that compiles to main.css

**Comment by kikoDevv** [comment]
Thanks for your feedback, the book.css file need to be compiled propriety meaning the the sections file is not property defined and it located inside a empty file called src. fixing the problem means compiling all the sass file inside the src/sections sassfiles again. thats way i did not compile the file in to main.css yet.

**Review by EmpyreanMist — APPROVED** [review]
Thank you for the fix, looks good!

**Pull request merged**
