### PR TITLE
Jp branch

### PR DESCRIPTION
**Pull request by SpinalGlitter**
Add styling to challenges cards.

### CODE REVIEW

**Review by EmpyreanMist — APPROVED** [review]
Tested the code, looks great.

**Review by kikoDevv — CHANGES_REQUESTED** [review]
Nicely done,  though a small issue with online and onsite cards having different height on cardBtn. Guessing due to the wrapping  text (p element) in card description  may cause some card with more text in card description to push button down by a bit.

**Comment by kikoDevv** [comment]
You need to tell the button to always stay at the end of the card. have you tried: align-items: end;  on onine-book-btn

**Comment by kikoDevv** [comment]
or we can fix it later on in our meeting no worries

**Review by kikoDevv — APPROVED** [review]
Nicely done.  We should try to avoid hard coding our element as much as possible so we dont run often to overflowing issue.

**Comment by EmpyreanMist** [comment]
Nice fix!

**Comment by EmpyreanMist** [comment]
Good job on resolving conflict, mergin.

**Pull request merged**
